version: '2'

services:
  micro-frontend-app1:
    container_name: micro-frontend-app1
    build: app1
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "3001:9015"

  micro-frontend-app2:
    container_name: micro-frontend-app2
    build: app2
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "3002:9015"
  
  micro-frontend-container:
    container_name: micro-frontend-container
    build: container
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "3003:9015"

  micro-frontend-nginx:
    container_name: micro-frontend-nginx
    build: nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "3005:80"
    depends_on:
      - micro-frontend-app1
      - micro-frontend-app2
      - micro-frontend-container