
version: "3.7"
services:
  order:
    container_name: order
    ports:
      - "8080:80"
    build:
      context: ./order

  trip:
    container_name: trip
    ports:
      - "8081:80"
    build:
      context: ./trip

  dashboard:
    container_name: dashboard
    ports:
      - "8082:80"
    build:
      context: ./dashboard

  orchestrator:
    container_name: orchestrator
    ports:
      - 80:80
    depends_on:
      - order
      - trip
      - dashboard
    build:
      context: ./nginx
